#!/usr/bin/tclsh
source "oasys/test_utils/test-lib.tcl"
source "oasys/test_utils/run.tcl"

if {[llength $argv] < 2} {
    puts "run <net file> <test script> options..."
    puts ""
    puts "Required:"
    puts "    <net file>    Network testbed file"
    puts "    <test script> Test script"
    puts ""
    usage
    exit
}

set [lindex $argv 0]