static const char* INIT_COMMAND = 
"#\n"
"# This file is converted into a big C string during the build\n"
"# process and evaluated in the command interpreter at startup\n"
"# time.\n"
"#\n"
"\n"
"package require tclreadline\n"
"\n"
"# Run the command loop with the given prompt\n"
"proc command_loop {prompt} {\n"
"    global command_prompt\n"
"    set command_prompt $prompt\n"
"\n"
"    namespace eval tclreadline {\n"
"	proc prompt1 {} {\n"
"	    global command_prompt\n"
"	    return \"${command_prompt}% \"\n"
"	}\n"
"    }\n"
"\n"
"    tclreadline::Loop\n"
"}\n"
"\n"
"# Define a bgerror proc to print the error stack when errors occur in\n"
"# event handlers\n"
"proc bgerror {err} {\n"
"    global errorInfo\n"
"    puts \"tcl error: $err\n$errorInfo\"\n"
"}\n"
"\n"
;
