static const char* INIT_COMMAND = 
"#\n"
"# This file is converted into a big C string during the build\n"
"# process and evaluated in the command interpreter at startup\n"
"# time.\n"
"#\n"
"\n"
"if [catch {\n"
"    error \"test\"\n"
"    package require tclreadline\n"
"\n"
"    # Run the command loop with the given prompt\n"
"    proc command_loop {prompt} {\n"
"	global command_prompt\n"
"	set command_prompt $prompt\n"
"\n"
"	namespace eval tclreadline {\n"
"	    proc prompt1 {} {\n"
"		global command_prompt\n"
"		return \"${command_prompt}% \"\n"
"	    }\n"
"	}\n"
"\n"
"	tclreadline::Loop\n"
"    }\n"
"} err] {\n"
"    log /tcl WARNING \"can't load tclreadline: $err\"\n"
"    log /tcl WARNING \"no command loop available\"\n"
"    \n"
"\n"
"    # Set up a dummy proc to run a \"command loop\" that just waits\n"
"    # forever in the tcl event loop\n"
"    proc command_loop {prompt} {\n"
"	global forever\n"
"	vwait forever\n"
"    }\n"
"}\n"
"\n"
"# Define a bgerror proc to print the error stack when errors occur in\n"
"# event handlers\n"
"proc bgerror {err} {\n"
"    global errorInfo\n"
"    puts \"tcl error: $err\n$errorInfo\"\n"
"}\n"
"\n"
;
