static const char* INIT_COMMAND = 
"#\n"
"# This file is converted into a big C string during the build\n"
"# process and evaluated in the command interpreter at startup\n"
"# time.\n"
"#\n"
"\n"
"# For the vwait to work, we need to make sure there's at least one\n"
"# event outstanding at all times, otherwise the 'vwait forever' trick\n"
"# below doesn't work\n"
"proc event_sched {} {\n"
"    after 1000000 event_sched\n"
"}\n"
"\n"
"# Run the event loop and no interpreter\n"
"proc event_loop {} {\n"
"    event_sched\n"
"    global forever\n"
"    vwait forever\n"
"}\n"
"    \n"
"# Run the command loop with the given prompt\n"
"proc command_loop {prompt} {\n"
"    if [catch {\n"
"	package require tclreadline\n"
"	global command_prompt\n"
"	set command_prompt $prompt\n"
"	namespace eval tclreadline {\n"
"	    proc prompt1 {} {\n"
"		global command_prompt\n"
"		return \"${command_prompt}% \"\n"
"	    }\n"
"	}\n"
"\n"
"	tclreadline::Loop\n"
"    } err] {\n"
"	log /tcl WARNING \"can't load tclreadline: $err\"\n"
"	log /tcl WARNING \"no command loop available\"\n"
"\n"
"	event_loop\n"
"    }\n"
"}\n"
"\n"
"# Define a bgerror proc to print the error stack when errors occur in\n"
"# event handlers\n"
"proc bgerror {err} {\n"
"    global errorInfo\n"
"    puts \"tcl error: $err\n$errorInfo\"\n"
"}\n"
"\n"
;
