.\" IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING. By
.\" downloading, copying, installing or using the software you agree to
.\" this license. If you do not agree to this license, do not download,
.\" install, copy or use the software.
.\" 
.\" Intel Open Source License
.\" 
.\" Copyright (c) 2004 Intel Corporation. All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are
.\" met:
.\" 
.\"   Redistributions of source code must retain the above copyright
.\"   notice, this list of conditions and the following disclaimer.
.\" 
.\"   Redistributions in binary form must reproduce the above copyright
.\"   notice, this list of conditions and the following disclaimer in the
.\"   documentation and/or other materials provided with the distribution.
.\" 
.\"   Neither the name of the Intel Corporation nor the names of its
.\"   contributors may be used to endorse or promote products derived from
.\"   this software without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE INTEL OR
.\" ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.TH dtnsend 1 "September 4, 2005"
.LO 1
.SH NAME
dtnsend \- send DTN bundles
.SH SYNOPSIS
.B dtnsend 
.RB -s 
.IR src
.RB -d 
.IR dest
.RB -t
.IR m|f|d
.RB -p 
.IR payload
.RB [ -r 
.IR reply-to ]
.RB [ -n
.IR num ]
.RB [ -i 
.IR regid ]
.RB [ -e 
.IR seconds ]
.RB [ \-chvwCDFR ]

.SH DESCRIPTION
.B dtnsend
injects a bundle into a DTN. To do this, it connects
to a dtnd daemon using the DTN API. If
.B \-\^w
was specified, it registers to receive any bundle status
reports that arrive for the reply-to EID (or the source-EID,
if the reply-to EID was not specified).
.PP
Once it has connected to the dtnd and registered, it enters
a loop, sending payloads and receiving status reports until
the number of bundles requested have been sent.

.SH RETURN VALUES
Returns 1 if there was an error processing the arguments.
Otherwise 
.B dtnsend
returns 0.

.SH OPTIONS
.TP
.B \-\^c
Request custody transfer. (Not currently implemented in dtnd.)
.TP
.B \-\^C
Request custody transfer receipts. (Not currently implemented in dtnd.)
.TP
.B \-\^d
The destination EID for the bundle. (Required)
.TP
.B \-\^D
Request an end-to-end delivery receipt.
.TP
.B \-\^e
The number of seconds until the bundle expires from the DTN. Default
is 3600 (one hour).
.TP
.B \-\^F
Request bundle forwarding receipts from every hop along the way.
.TP
.B \-\^i
The registration ID to pass in to dtnd when registering.
(Not currently implemented in DTN API.)
.TP
.B \-\^n
The number of bundles to send.
.TP
.B \-\^r
The reply-to EID for the bundle. If it is not specified, the
source EID is used by default.
.TP
.B \-\^R
Request bundle reception receipts from every hop along the way.
.TP
.B \-\^s
The source EID for the bundle. It should be an endpoint for which
the dtnd is responsible, but that is not currently enforced.
(Required)
.TP
.B \-\^t
Type of payload. Can be `m' for memory, `f' for file, or `d' for
date. If type is `m', the
.B \-\^p
argument is used as the payload, byte for byte. If type is `f'
the
.B \-\^p
argument is used as a filename which holds the bundle data. dtnd
must have read permission for the file, as it will be the process
reading the file, not
.BR dtnsend .
If type
is `d' the current date is put into the bundle, and any
.B \-\^p
argument is ignored. (Required)
.TP
.B \-\^h
Print a one-line help message and exit.
.TP
.B \-\^p
The payload (when type is `m'), or the filename (when type is `f').
Ignored when type is `d'.
.TP
.B \-\^v
Be verbose. Adds diagnostic information to the standard output.
.TP
.B \-\^w
After sending every payload, wait for one reply and print it.
Note that it is currently impossible to see multiple replies with
the
.B \-\^w
option. Instead, use
.B dtnrecv
in another window.

.SH ENVIRONMENT
.TP
.B DTNAPI_ADDR
If
.B DTNAPI_ADDR
is set, 
.B dtnsend
uses it as the hostname to connect to for DTN API operations.
.TP
.B DTNAPI_PORT
If
.B DTNAPI_PORT
is set, its value is used as the TCP port to connect to
for DTN API operations.
.SH "SEE ALSO"
dtnrecv(1), dtnd(8).
.SH BUGS
When
.B dtnsend
is listening for replies, it blocks and waits forever. If no response
comes, it will never get around to sending the rest of the bundles
it was requested to send. It would be better if it displayed bundle
replies as the arrived instead, without blocking.
