/*
 *    Copyright 2006 Intel Corporation
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifdef HAVE_CONFIG_H
#  include <dtn-config.h>
#endif

#include <memory.h> /* for memset */
#include "gateway_prot.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
bamboo_dht_proc_null_2(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, BAMBOO_DHT_PROC_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

bamboo_stat *
bamboo_dht_proc_put_2(bamboo_put_args *argp, CLIENT *clnt)
{
	static bamboo_stat clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, BAMBOO_DHT_PROC_PUT,
		(xdrproc_t) xdr_bamboo_put_args, (caddr_t) argp,
		(xdrproc_t) xdr_bamboo_stat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bamboo_get_res *
bamboo_dht_proc_get_2(bamboo_get_args *argp, CLIENT *clnt)
{
	static bamboo_get_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, BAMBOO_DHT_PROC_GET,
		(xdrproc_t) xdr_bamboo_get_args, (caddr_t) argp,
		(xdrproc_t) xdr_bamboo_get_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
