#!/bin/bash

if [ ! -f version.dat ] ; then
   echo "can't find version.dat" 
   exit 1
fi

if [ '$0' = '' ] ; then
   echo "usage: bump-version <package name>"
fi

major=`awk '{print $1}' < version.dat`
minor=`awk '{print $2}' < version.dat`
patch=`awk '{print $3}' < version.dat`

patch=`expr $patch + 1`

echo "$major $minor $patch" > version.dat
